version: "3"
services:
  backend:
    image: distributed_backend
    environment:
      APP_VERSION: 1.0.0
      PORT: 8080
      MODE: Development
      JWT_SECRET_KEY: secretkey
      COOKIE_NAME: inv-token
      READ_TIMEOUT: 5
      WRITE_TIMEOUT: 5
      SSL: "true"
      CTX_DEFAULT_TIMEOUT: 12
      CSRF: "true"
      DEBUG: "false"
      MAX_CONNECTION_IDLE: 5
      TIMEOUT: 15
      MAX_CONNECTION_AGE: 5
      TIME: 120
      SERVICE_NAME: backend
      TIME_CONVERT: "2006-01-02"
    ports:
      - 8080:8080

  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: 12345678
      ACCEPT_EULA: Y
    ports:
      - 3306:1433

  redis:
    image: redis
    environment:
      REDIS_PASSWORD: 12345678
    ports:
      - 6379:6379
