server:
    AppVersion: 1.0.0
    Port: :8080
    Mode: Development
    JwtSecretKey: secretkey
    CookieName: authscv-token
    ReadTimeout: 5
    WriteTimeout: 5
    SSL: true
    CtxDefaultTimeout: 12
    CSRF: true
    Debug: false
    MaxConnectionIdle: 5
    Timeout: 15
    MaxConnectionAge: 5
    Time: 120
    ServiceName: distributed_database_server
    TimeConvert: '2006-01-02'
    
Auth:
  JWTSecret: "your_jwt_secret"
  Expire: 3600
  Issuer: "your_issuer"
  Audience: "your_audience"

Redis:
  Host: "localhost"
  Port: 6379
  PoolSize: 12000
  PoolTimeout: 240
  MinIdleConns: 200
  DB: 0
  Username: "your_username"
  Password: "your_password"

PostgreSQL:
  Host: "localhost"
  Port: 5432
  User: postgres
  Password: changeme
  DBName: database1

Server:
  AppVersion: "1.0.0"
  Port: 8080
  Mode: "Development"
  ReadTimeout: 5
  WriteTimeout: 5
  SSL: true
  CtxDefaultTimeout: 12
  Debug: false