version: "3.5"

services:
  postgres:
    container_name: distributed-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      DBName: database1
    ports:
      - "5432:5432"
    restart: unless-stopped
